version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/codecake?currentSchema=ecommerce_yt
      - SPRING_DATASOURCE_USERNAME=codecake
      - SPRING_DATASOURCE_PASSWORD=codecake
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=codecake
      - POSTGRES_PASSWORD=codecake
      - POSTGRES_DB=codecake
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codecake -d codecake"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 